services:
  admission-controller:
    image: ghcr.io/haukuen/derper-admission-controller:latest
    container_name: admission-controller
    restart: unless-stopped
    volumes:
      - ./whitelist.txt:/etc/derper/whitelist.txt
    ports:
      - "8081:8081"
    environment:
      # - TS_SYNC_CLIENTS=k1234567890abcdef:tskey-client-xxxx

  derper:
    image: ghcr.io/haukuen/derper:latest
    container_name: derper
    restart: unless-stopped
    environment:
      - DERP_HOSTNAME=<your_server_public_ip>
      - VERIFY_CLIENT_URL=http://admission-controller:8081/verify
    ports:
      - "40007:40007/tcp"
      - "40008:40008/udp"
    volumes:
      - ./derper-certs:/var/lib/derper
    depends_on:
      - admission-controller
